# Generated by Django 5.0.1 on 2024-01-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_good_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='image',
        ),
        migrations.AddField(
            model_name='good',
            name='article',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='артикул'),
        ),
        migrations.AddField(
            model_name='good',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='цвет'),
        ),
        migrations.AddField(
            model_name='good',
            name='color_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='код цвета'),
        ),
        migrations.AddField(
            model_name='good',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='good',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='изображение 1'),
        ),
        migrations.AddField(
            model_name='good',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='изображение 2'),
        ),
        migrations.AddField(
            model_name='good',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='изображение 3'),
        ),
        migrations.AddField(
            model_name='good',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='изображение 4'),
        ),
        migrations.AddField(
            model_name='good',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='новинка'),
        ),
        migrations.AddField(
            model_name='good',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='цена'),
        ),
        migrations.AddField(
            model_name='good',
            name='size',
            field=models.IntegerField(blank=True, choices=[(0, 'XS'), (1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'XXL')], null=True, verbose_name='размер'),
        ),
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='телефон'),
        ),
    ]
