# Generated by Django 5.0.1 on 2024-01-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_good_image_good_article_good_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='size',
        ),
    ]
