# Generated by Django 5.0.1 on 2024-01-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_good_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Мужское'), (1, 'Женское'), (2, 'Детское')], null=True, verbose_name='пол'),
        ),
    ]
