# Generated by Django 5.0.1 on 2024-01-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_good_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='material',
            field=models.TextField(blank=True, null=True, verbose_name='состав'),
        ),
        migrations.AddField(
            model_name='good',
            name='recommendation',
            field=models.TextField(blank=True, null=True, verbose_name='рекомендации'),
        ),
    ]
