# Generated by Django 5.0.1 on 2024-01-28 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_cartgood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartgood',
            name='cartThrough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='shop.cart'),
        ),
        migrations.AlterField(
            model_name='cartgood',
            name='goodThrough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to='shop.good'),
        ),
    ]
