# Generated by Django 5.0.1 on 2024-01-28 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_cartgood_cartthrough_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='goods',
            field=models.ManyToManyField(through='shop.CartGood', to='shop.good'),
        ),
        migrations.AddField(
            model_name='good',
            name='goods',
            field=models.ManyToManyField(through='shop.CartGood', to='shop.cart'),
        ),
        migrations.AlterField(
            model_name='cartgood',
            name='cartThrough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart'),
        ),
        migrations.AlterField(
            model_name='cartgood',
            name='goodThrough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.good'),
        ),
    ]
