# Generated by Django 5.0.1 on 2024-02-02 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_cart_goods_good_goods_alter_cartgood_cartthrough_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
