# Generated by Django 5.0.1 on 2024-02-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='building',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='дом'),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='дата доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='flat',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='квартира'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='интервал доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(blank=True, null=True, verbose_name='сумма'),
        ),
    ]
