# Generated by Django 5.0.1 on 2024-02-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_address_order_building_order_date_order_flat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='улица'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_period',
            field=models.IntegerField(blank=True, choices=[(1, '9:00 - 21:00'), (1, '9:00 - 15:00'), (1, '15:00 - 21:00'), (1, '9:00 - 13:00'), (1, '13:00 - 17:00'), (1, '17:00 - 21:00')], null=True, verbose_name='интервал доставки'),
        ),
    ]
