# Generated by Django 5.0.1 on 2024-02-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_order_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
    ]
