# Generated by Django 5.0.1 on 2024-02-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_order_delivery_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='goods',
            new_name='carts',
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.FloatField(blank=True, default='1000', null=True, verbose_name='сумма'),
        ),
    ]
