# Generated by Django 5.0.1 on 2024-02-08 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_rename_goods_good_carts_alter_order_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.good')),
                ('orderThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='orders',
            field=models.ManyToManyField(through='shop.OrderGood', to='shop.order'),
        ),
        migrations.AddField(
            model_name='order',
            name='goods',
            field=models.ManyToManyField(through='shop.OrderGood', to='shop.good'),
        ),
    ]
