# Generated by Django 5.0.1 on 2024-02-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_ordergood_good_orders_order_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='goods',
            field=models.ManyToManyField(blank=True, through='shop.OrderGood', to='shop.good'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, null=True, verbose_name='Ответ службы поддержки'),
        ),
    ]
